package com.anezium.rokidlive.phone

import com.anezium.rokidlive.shared.ChatOverlayMessage
import com.anezium.rokidlive.shared.Protocol
import com.anezium.rokidlive.shared.VideoPreset

data class PhoneUiState(
    val requiredRokidAppInstalled: Boolean = false,
    val authorized: Boolean = false,
    val cxrConnected: Boolean = false,
    val glassBtConnected: Boolean = false,
    val glassesBatteryPercent: Int = -1,
    val receiverRunning: Boolean = false,
    val reverseRunning: Boolean = false,
    val streaming: Boolean = false,
    val p2pRunning: Boolean = false,
    val p2pConnected: Boolean = false,
    val p2pStatus: String = "",
    val p2pPeer: String = "",
    val p2pEndpoint: String = "",
    val selectedPreset: VideoPreset = VideoPreset.Default,
    val previewRotationDegrees: Int = VideoPreset.Default.displayRotationDegrees,
    val youtubeStreamKey: String = "",
    val youtubeTitle: String = "",
    val youtubeDescription: String = "",
    val youtubePrivacy: YoutubePrivacy = YoutubePrivacy.Default,
    val youtubeCategoryId: String = YoutubeCategory.Default.id,
    val youtubeDeviceClientId: String = "",
    val youtubeDeviceClientSecret: String = "",
    val youtubeDeviceUserCode: String = "",
    val youtubeDeviceVerificationUrl: String = "",
    val youtubeDeviceAuthPending: Boolean = false,
    val youtubeConnected: Boolean = false,
    val youtubeAccount: String = "",
    val youtubeChannelId: String = "",
    val youtubeChannelTitle: String = "",
    val youtubeBroadcastId: String = "",
    val youtubeStreamId: String = "",
    val youtubeWatchUrl: String = "",
    val youtubeIngestionAddress: String = "",
    val youtubeVideoBitrateOverride: Int = 0,
    val youtubeLive: Boolean = false,
    val youtubeChatEnabled: Boolean = false,
    val youtubeChatFontSizeSp: Int = Protocol.DEFAULT_CHAT_FONT_SIZE_SP,
    val youtubeChatMaxMessages: Int = Protocol.DEFAULT_CHAT_MAX_MESSAGES,
    val youtubeChatStatus: String = "",
    val youtubeChatMessages: List<ChatOverlayMessage> = emptyList(),
    val youtubeStatus: String = "",
    val youtubeBytesSent: Long = 0,
    val phoneIp: String = "",
    val helperNetworkInfo: String = "",
    val sessionToken: String = "",
    val lastStatus: String = "",
    val framesReceived: Long = 0,
    val bytesReceived: Long = 0,
    val droppedFrames: Long = 0,
    val error: String = ""
)
